spring:
  application:
    name: Migration Service
  datasource:
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:12345}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    clean-disabled: true
    connect-retries: 3
    group: false
    schemas:
      - main
      - voucher
      - storage
    create-schemas: true
    table: flyway_schema_history
    mixed: false
    out-of-order: false
    encoding: UTF-8
    driver-class-name: org.postgresql.Driver
    baseline-on-migrate: true
    validate-on-migrate: true
    baseline-version: 1
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME}
    user: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:12345}

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    org.springframework.amqp: DEBUG
    org.springframework.messaging: DEBUG
    org.springframework.retry: DEBUG