apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: sea-local
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432