apiVersion: v1
kind: Namespace
metadata:
  name: sea-local
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dataabse-service
  namespace: sea-local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database-service
  template:
    metadata:
      labels:
        app: database-service
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: database-service
  namespace: sea-local
spec:
  selector:
    app: database-service
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-service
  namespace: sea-local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-service
  template:
    metadata:
      labels:
        app: redis-service
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: sea-local
spec:
  selector:
    app: redis-service
  ports:
    - port: 6379
      targetPort: 6379

