spring:
  application:
      name: API Gateways
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: main-service-route
          uri: http://${MAIN_SERVICE_HOST:localhost}:${MAIN_SERVICE_PORT:8080}
          predicates:
          - Path=/api/v1/main/**
          filters:
          - StripPrefix=3
        - id: voucher-service-route
          uri: http://${VOUCHER_SERVICE_HOST:localhost}:${VOUCHER_SERVICE_PORT:8084}
          predicates:
          - Path=/api/v1/voucher/**
          filters:
          - StripPrefix=3
        - id: storage-service-route
          uri: http://${STORAGE_SERVICE_HOST:localhost}:${STORAGE_SERVICE_PORT:8083}
          predicates:
          - Path=/api/v1/storage/**
          filters:
          - StripPrefix=3
        - id: account-service-route
          uri: http://${ACCOUNT_SERVICE_HOST:localhost}:${ACCOUNT_SERVICE_PORT:8082}
          predicates:
          - Path=/api/v1/account/**
          filters:
          - StripPrefix=3
        - id: feedback-notification-service-route
          uri: http://${FEEDBACK_SERVICE_HOST:localhost}:${FEEDBACK_SERVICE_PORT:8085}
          predicates:
          - Path=/api/v1/feedback/**
          filters:
          - StripPrefix=3

server:
  port: ${PORT:8080}
  servlet:
    context-path: ${CONTEXT_PATH:/api/v1}