spring:
  application:
      name: API Gateways
  main:
    web-application-type: reactive
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        enabled: true
        prefer-ip-address: true
        service-name: api-gateway
        health-check-interval: 10s
        instance-id: api-gateway
        health-check-path: /actuator/health
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service-route
          uri: lb://user-service
          predicates:
          - Path=/api/v1/users/**
          filters:
          - StripPrefix=3

server:
  port: ${PORT:8080}