services:
  dev-consul:
    container_name: dev_consul
    image: consul:1.15.4
    ports:
      - 8600:8600
      - 8500:8500
    environment:
      CONSUL_BIND_INTERFACE: eth0
    networks:
      - vns-networks-dev
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: vns
    networks:
      - vns-networks-dev

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 5051:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    networks:
      - vns-networks-dev

networks:
  vns-networks-dev:
    name: vns-networks-dev