spring:
  application:
    name: Catalog Service
  config:
    import: "optional:consul:"
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        enabled: true
        prefer-ip-address: true
        service-name: catalog-service
        health-check-interval: 10s
        instance-id: catalog-service
        health-check-path: /actuator/health
  grpc:
    server:
      enabled: true
      port: ${GRPC_PORT:9080}
  data:
    mongodb:
      database: ${MONGO_DB:retrade}
      host: ${MONGO_HOST:localhost}
      username: ${MONGO_USER:root}
      password: ${MONGO_PASS:example}
      port: 27017
      authentication-database: admin
      auto-index-creation: true
    redis:
      port: ${REDIS_PORT:6379}
      host: ${REDIS_HOST:localhost}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: ${PORT:8080}
  servlet:
    context-path: /api/v1
  host:
    origin-allows: ${ORIGIN_ALLOWS:}
    base-host: ${BASE_HOST:}

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    try-it-out-enabled: true
    operations-sorter: method
    tags-sorter: alpha
    filter: true
    path: /swagger-ui
