services:
  database-services:
    container_name: database_service
    image: postgres:latest
    restart: always
    networks:
      - rt-local-networks
    profiles:
      - database
      - local
      - storage
  redis-services:
    container_name: redis_service
    image: redis:latest
    restart: always
    networks:
      - rt-local-networks
    profiles:
      - database
      - local
      - storage
  rabbitmq-services:
    container_name: rabbitmq_service
    image: rabbitmq:3-management
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - rt-local-networks
    profiles:
      - database
      - local
      - storage
  main-services:
    container_name: main_service
    image: main-authentication-service:latest
    restart: always
    build:
      context: ..
      dockerfile: services/main/Dockerfile
    networks:
      - rt-local-networks
    profiles:
      - backend
      - local
      - main
  feedback-notification-services:
    container_name: feedback_notification_service
    image: sea-feedback-notification-service:latest
    restart: always
    build:
      context: ..
      dockerfile: services/feedback-notification/Dockerfile
    networks:
      - rt-local-networks
    profiles:
      - backend
      - local
      - feedback-notification
  vouche-services:
    container_name: voucher_service
    image: voucher-service:latest
    restart: always
    build:
      context: ..
      dockerfile: services/voucher/Dockerfile
    networks:
      - rt-local-networks
    profiles:
      - backend
      - local
      - voucher
  gateway-services:
    container_name: gateway_services
    image: gateway-service:latest
    build:
      context: ..
      dockerfile: services/gateway/Dockerfile
    networks:
      - rt-local-networks
    profiles:
      - backend
      - local
      - gateway
  consul-services:
    container_name: consul_service
    image: consul:latest
    restart: always
    networks:
      - rt-local-networks
    profiles:
      - consul
      - local
      - consul
networks:
  rt-local-networks:
    name: rt-local-networks