services:
  database-services:
    container_name: database_service
    image: postgres:latest
    restart: always
    networks:
      - sea-local-networks
    profiles:
      - database
      - local
      - storage
  redis-services:
    container_name: redis_service
    image: redis:latest
    restart: always
    networks:
      - sea-local-networks
    profiles:
      - database
      - local
      - storage
  authentication-services:
    container_name: authentication_service
    image: sea-authentication-service:latest
    restart: always
    build:
      context: ..
      dockerfile: services/authentication/Dockerfile
    networks:
      - sea-local-networks
    profiles:
      - backend
      - local
      - authentication
  account-services:
    container_name: account_service
    image: sea-account-service:latest
    restart: always
    build:
      context: ..
      dockerfile: services/account/Dockerfile
    networks:
      - sea-local-networks
    profiles:
      - backend
      - local
      - account
  booking-payment-services:
    container_name: booking_payment_service
    image: sea-booking-payment-service:latest
    build:
      context: ..
      dockerfile: services/booking-payment/Dockerfile
    networks:
      - sea-local-networks
    profiles:
      - backend
      - local
      - booking-payment
  feedback-notification-services:
    container_name: feedback_notification_service
    image: sea-feedback-notification-service:latest
    restart: always
    build:
      context: ..
      dockerfile: services/feedback-notification/Dockerfile
    networks:
      - sea-local-networks
    profiles:
      - backend
      - local
      - feedback-notification
  partner-services:
    container_name: partner_service
    image: partner-service:latest
    restart: always
    build:
      context: ..
      dockerfile: services/partner/Dockerfile
    networks:
      - sea-local-networks
    profiles:
      - backend
      - local
      - partner
  user-services:
    container_name: user_service
    image: user-service:latest
    restart: always
    build:
      context: ..
      dockerfile: services/user/Dockerfile
    networks:
      - sea-local-networks
    profiles:
      - backend
      - local
      - user
  gateway-services:
    container_name: gateway_services
    image: gateway-service:latest
    build:
      context: ..
      dockerfile: services/gateway/Dockerfile
    networks:
      - sea-local-networks
    profiles:
      - backend
      - local
      - gateway
  consul-services:
    container_name: consul_service
    image: consul:latest
    restart: always
    networks:
      - sea-local-networks
    profiles:
      - consul
      - local
      - consul
networks:
  sea-local-networks:
    name: sea-local-networks