services:
  main-services:
    image: ${REGISTRY}/rt-main-service:latest
    build:
      context: ..
      dockerfile: services/main/Dockerfile
    profiles:
      - backend
      - build
      - main
  feedback-notification-services:
    image: ${REGISTRY}/rt-feedback-notification-service:latest
    build:
      context: ..
      dockerfile: services/feedback-notification/Dockerfile
    profiles:
      - backend
      - build
      - feedback-notification
  voucher-services:
    image: ${REGISTRY}/rt-voucher-service:latest
    build:
      context: ..
      dockerfile: services/voucher/Dockerfile
    profiles:
      - backend
      - build
      - voucher
  gateway-services:
    image: ${REGISTRY}/rt-gateway-service:latest
    build:
      context: ..
      dockerfile: services/gateway/Dockerfile
    profiles:
      - backend
      - build
      - gateway