services:
  main-services:
    image: ${REGISTRY}/rt-main-service:latest
    build:
      context: ..
      dockerfile: services/main/Dockerfile
    profiles:
      - backend
      - build
      - main
  feedback-notification-services:
    image: ${REGISTRY}/rt-feedback-notification-service:latest
    build:
      context: ..
      dockerfile: services/feedback-notification/Dockerfile
    profiles:
      - backend
      - build
      - feedback-notification
  voucher-services:
    image: ${REGISTRY}/rt-voucher-service:latest
    build:
      context: ..
      dockerfile: services/voucher/Dockerfile
    profiles:
      - backend
      - build
      - voucher
  storage-services:
    image: ${REGISTRY}/rt-storage-service:latest
    build:
      context: ..
      dockerfile: services/storage/Dockerfile
    profiles:
      - backend
      - build
      - storage
  prover-services:
    image: ${REGISTRY}/rt-prover-service:latest
    build:
      context: ..
      dockerfile: services/prover/Dockerfile
    profiles:
      - backend
      - build
      - prover
  gateway-services:
    image: ${REGISTRY}/rt-gateway-service:latest
    build:
      context: ..
      dockerfile: services/gateway/Dockerfile
    profiles:
      - backend
      - build
      - gateway
  api-docs:
    image: ${REGISTRY}/rt-api-docs:latest
    build:
      context: ../api-docs
      dockerfile: Dockerfile
    profiles:
      - backend
      - build
      - docs