services:
  main-services:
    image: ${REGISTRY}/rt-main-service
    build:
      context: ..
      dockerfile: services/main/Dockerfile
      tags:
        - ${REGISTRY}/rt-main-service:latest
        - ${REGISTRY}/rt-main-service:${TAG}
    profiles:
      - backend
      - build
      - main
  feedback-notification-services:
    image: ${REGISTRY}/rt-feedback-notification-service
    build:
      context: ..
      dockerfile: services/feedback-notification/Dockerfile
      tags:
        - ${REGISTRY}/rt-feedback-notification-service:latest
        - ${REGISTRY}/rt-feedback-notification-service:${TAG}
    profiles:
      - backend
      - build
      - feedback-notification
  voucher-services:
    image: ${REGISTRY}/rt-voucher-service
    build:
      context: ..
      dockerfile: services/voucher/Dockerfile
      tags:
        - ${REGISTRY}/rt-voucher-service:latest
        - ${REGISTRY}/rt-voucher-service:${TAG}
    profiles:
      - backend
      - build
      - voucher
  storage-services:
    image: ${REGISTRY}/rt-storage-service
    build:
      context: ..
      dockerfile: services/storage/Dockerfile
      tags:
        - ${REGISTRY}/rt-storage-service:latest
        - ${REGISTRY}/rt-storage-service:${TAG}
    profiles:
      - backend
      - build
      - storage
  prover-services:
    image: ${REGISTRY}/rt-prover-service
    build:
      context: ..
      dockerfile: services/prover/Dockerfile
      tags:
        - ${REGISTRY}/rt-prover-service:latest
        - ${REGISTRY}/rt-prover-service:${TAG}
    profiles:
      - backend
      - build
      - prover
  migration-services:
    image: ${REGISTRY}/rt-migration-service
    build:
      context: ..
      dockerfile: services/migration/Dockerfile
      tags:
        - ${REGISTRY}/rt-migration-service:latest
        - ${REGISTRY}/rt-migration-service:${TAG}
    profiles:
      - backend
      - build
      - migration
  gateway-services:
    image: ${REGISTRY}/rt-gateway-service:latest
    build:
      context: ..
      dockerfile: services/gateway/Dockerfile
    profiles:
      - backend
      - build
      - gateway
  api-docs:
    image: ${REGISTRY}/rt-api-docs:latest
    build:
      context: ../api-docs
      dockerfile: Dockerfile
    profiles:
      - backend
      - build
      - docs