services:
  api-gateways:
    container_name: vietnamsea_gateway
    image: vietnamsea-api-gateways:latest
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints: [node.rode == manager]
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
    ports:
      - 8080:8080

  user-services:
    container_name: vietnamsea_user_service
    image: vietnamsea-user-service:latest
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == worker]
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
        failure_action: continue
      rollback_config:
        parallelism: 1
        delay: 10s
        monitor: 30s
        max_failure_ratio: 0.2
        failure_action: rollback
      resources:
        limits:
          cpus: '1.0'
          memory: 1G

  payment-services:
    container_name: vietnamsea_payment_service
    image: vietnamsea-payment-service:latest
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == worker]
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
        failure_action: continue
      rollback_config:
        parallelism: 1
        delay: 10s
        monitor: 30s
        max_failure_ratio: 0.2
        failure_action: rollback
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
  booking-services:
    container_name: vietnamsea_booking_service
    image: vietnamsea-booking-service:latest
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 1G
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: continue
      rollback_config:
        parallelism: 1
        delay: 10s
        monitor: 30s
        max_failure_ratio: 0.2
        failure_action: rollback

networks:
  vietnamsea-networks:
    name: vietnamsea_networks
    driver: overlay
    attachable: true