services:
  main-service:
    container_name: main_service
    image: main-authentication-service:latest
    restart: always
    networks:
      - rt-prod-networks
    profiles:
      - backend
      - prod
      - main
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.main-service.rule=PathPrefix(`/api/main/v1/`)"
      - "traefik.http.routers.main-service.entrypoints=web"
      - "traefik.http.routers.main-service.tls=true"
      - "traefik.http.services.main-service.loadbalancer.server.port=8080"

  feedback-notification-service:
    container_name: feedback_notification_service
    image: rt-feedback-notification-service:latest
    restart: always
    networks:
      - rt-prod-networks
    profiles:
      - backend
      - prod
      - feedback-notification
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.feedback-service.rule=PathPrefix(`/api/feedback-notification/v1/`)"
      - "traefik.http.routers.feedback-service.entrypoints=web"
      - "traefik.http.routers.feedback-service.tls=true"
      - "traefik.http.services.feedback-service.loadbalancer.server.port=8080"

  storage-service:
    container_name: feedback_notification_service
    image: rt-storage-service:latest
    restart: always
    networks:
      - rt-prod-networks
    profiles:
      - backend
      - prod
      - feedback-notification
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.feedback-service.rule=PathPrefix(`/api/storage/v1/`)"
      - "traefik.http.routers.feedback-service.entrypoints=web"
      - "traefik.http.routers.feedback-service.tls=true"
      - "traefik.http.services.feedback-service.loadbalancer.server.port=8080"

  voucher-service:
    container_name: voucher_service
    image: voucher-service:latest
    restart: always
    networks:
      - rt-prod-networks
    profiles:
      - backend
      - prod
      - voucher
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.voucher-service.rule=PathPrefix(`/api/voucher/v1/`)"
      - "traefik.http.routers.voucher-service.entrypoints=web"
      - "traefik.http.routers.voucher-service.tls=true"
      - "traefik.http.services.voucher-service.loadbalancer.server.port=8080"

  consul-service:
    container_name: consul_service
    image: consul:latest
    restart: always
    networks:
      - rt-prod-networks
    profiles:
      - prod
      - consul
    labels:
      - "traefik.enable=false"
networks:
  rt-prod-networks:
    name: rt-prod-networks
