services:
  dev-consul:
    container_name: dev_consul
    restart: always
    image: consul:1.15.4
    ports:
      - 8600:8600
      - 8500:8500
    environment:
      CONSUL_BIND_INTERFACE: eth0
    networks:
      vns-networks-dev:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: vns
    networks:
      vns-networks-dev:

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 5051:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    networks:
      vns-networks-dev:

  dev-postgres:
    image: postgres:14.12-bullseye
    container_name: vns_postgres_db
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: vns
    networks:
      vns-networks-dev:

  dev-pgadmin4:
    image: elestio/pgadmin:latest
    container_name: vns_pgadmin
    restart: always
    environment:
        PGADMIN_DEFAULT_EMAIL: admin@example.com
        PGADMIN_DEFAULT_PASSWORD: admin
        PGADMIN_LISTEN_PORT: 5050
    networks:
      vns-networks-dev:
    ports:
      - 5052:5050
  broker1:
    image: 'bitnami/kafka:latest'
    container_name: broker1
    restart: always
    environment:
      KAFKA_ENABLE_KRAFT: yes
      KAFKA_CFG_PROCESS_ROLES: 'broker,controller'
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://broker1:9092
      KAFKA_CFG_BROKER_ID: 1
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: '1@broker1:9093'
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_KRAFT_CLUSTER_ID: r4zt_wrqTRuT7W2NJsB_GA
    ports:
      - 9092:9092
      - 9093:9093
    networks:
      vns-networks-dev:
  kafka-ui:
    container_name: kafka-ui
    image: 'provectuslabs/kafka-ui:latest'
    restart: always
    depends_on:
      - broker1
    ports:
      - "8092:8080"
    environment:
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: 'broker1:9092'
      KAFKA_CLUSTERS_0_NAME: vns-dev-kafka-cluster
    networks:
      vns-networks-dev:
networks:
  vns-networks-dev:
    name: vns-networks-dev