server:
  port: 8083

spring:
  application:
    name: voucher-service
  datasource:
    url: jdbc:postgresql://localhost:5432/retrade_voucher
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  grpc:
    server:
      port: 9090
      address: localhost
      security:
        csrf:
          enabled: false

grpc:
  client:
    main-service:
      host: ${MAIN_SERVICE_GRPC_HOST:localhost}
      port: ${MAIN_SERVICE_GRPC_PORT:9080}

logging:
  level:
    org:
      springframework: INFO
      retrade: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    try-it-out-enabled: true
    operations-sorter: method
    tags-sorter: alpha
    filter: true
    path: /swagger-ui


