spring:
  application:
    name: Voucher Service
  datasource:
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:12345}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME}
  config:
    import: "optional:consul:"
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        enabled: true
        prefer-ip-address: true
        service-name: voucher-service
        health-check-interval: 10s
        instance-id: voucher-service
        health-check-path: /actuator/health
      config:
        enabled: true
        name: voucher-service

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: voucher
  grpc:
    server:
      enabled: true
      port: ${GRPC_PORT:9081}
      security:
        csrf:
          enabled: false

grpc:
  client:
    main-service:
      host: ${MAIN_SERVICE_GRPC_HOST:localhost}
      port: ${MAIN_SERVICE_GRPC_PORT:9080}

server:
  port: ${PORT:8084}
  servlet:
    context-path: /api/v1

logging:
  level:
    org:
      springframework: INFO
      retrade: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    try-it-out-enabled: true
    operations-sorter: method
    tags-sorter: alpha
    filter: true
    path: /swagger-ui


