spring:
  application:
      name: Auth Service
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        enabled: true
        prefer-ip-address: true
        service-name: authentication-service
        health-check-interval: 10s
        instance-id: authentication-service
        health-check-path: /actuator/health
  data:
    mongodb:
      database: ${MONGO_DB:vns}
      host: ${MONGO_HOST:localhost}
      username: ${MONGO_USER:root} 
      password: ${MONGO_PASS:example}
      port: 27017
      authentication-database: admin
      auto-index-creation: true

server:
  port: ${PORT:8081}


