spring:
  application:
      name: Auth Service
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        enabled: true
        prefer-ip-address: true
        service-name: authentication-service
        health-check-interval: 10s
        instance-id: authentication-service
        health-check-path: /actuator/health
  data:
    mongodb:
      database: ${MONGO_DB:vns}
      host: ${MONGO_HOST:localhost}
      username: ${MONGO_USER:root} 
      password: ${MONGO_PASS:example}
      port: 27017
      authentication-database: admin
      auto-index-creation: true
    redis:
      port: ${REDIS_PORT:6379}
      host: ${REDIS_HOST:localhost}

  datasource:
    url: jdbc:postgresql://${DB_URL:localhost}:${DB_PORT:5432}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: ${PORT:8081}

grpc:
  server:
    port: ${GRPC_PORT:9081}


token:
  jwt:
    access-token:
      key: ${JWT_ACCESS_KEY}
      ex-time: ${JWT_ACCESS_EX}
    refresh-token:
      key: ${JWT_REFRESH_KEY}
      ex-time: ${JWT_REFRESH_EX}