spring:
  application:
    name: Auth Service
  config:
    import: "optional:consul:"
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        enabled: true
        prefer-ip-address: true
        service-name: authentication-service
        health-check-interval: 10s
        instance-id: authentication-service
        health-check-path: /actuator/health
  grpc:
    server:
      enabled: true
      port: ${GRPC_PORT:9080}
  data:
    mongodb:
      database: ${MONGO_DB:retrade}
      host: ${MONGO_HOST:localhost}
      username: ${MONGO_USER:root}
      password: ${MONGO_PASS:example}
      port: 27017
      authentication-database: admin
      auto-index-creation: true
    redis:
      port: ${REDIS_PORT:6379}
      host: ${REDIS_HOST:localhost}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: ${PORT:8081}

security:
  token:
      jwt:
        access-token:
          key: ${JWT_ACCESS_KEY}
          max-age: ${JWT_ACCESS_EX:3000}
        refresh-token:
          key: ${JWT_REFRESH_KEY}
          max-age: ${JWT_REFRESH_EX:8000}
        twofa-token:
          key: ${JWT_2FA_KEY}
          max-age: ${JWT_2FA_EX:3000}
  host:
    origin-allows: ${ORIGIN_ALLOWS:}
    base-host: ${BASE_HOST:}
management:
  endpoints:
    web:
      exposure:
        include: health,info
  server:
    port: 8081