spring:
  application:
    name: Prover Service
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3
          max-interval: 10000
          multiplier: 2.0
        acknowledge-mode: manual
    address-shuffle-mode: inorder
logging:
  level:
    com.rabbitmq: DEBUG
    org.springframework.amqp.rabbit: DEBUG
    org.springframework.amqp.rabbit.listener: DEBUG
    org:
      retrade: DEBUG

fpt:
  base-url: ${FPT_BASE_URL:https://api.fpt.ai/vision/idr/vnm/}
  api-key: ${FPT_API_KEY:}


minio:
  url: ${MINIO_URL:http://localhost:9000}
  access-key: ${MINIO_ACCESS_KEY:}
  secret-key: ${MINIO_SECRET_KEY:}
  bucket-name: ${MINIO_BUCKET_NAME:retrade}

server:
  port: 8087


security:
  aes:
    key: ${AES_KEY:sus}