spring:
  application:
    name: Achievement Service
  datasource:
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:12345}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: achievement
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3
          max-interval: 10000
          multiplier: 2.0
        acknowledge-mode: manual
    address-shuffle-mode: inorder
  grpc:
    server:
      enabled: true
      port: ${GRPC_PORT:9081}
      security:
        csrf:
          enabled: false

grpc:
  client:
    main-service:
      host: ${MAIN_SERVICE_GRPC_HOST:localhost}
      port: ${MAIN_SERVICE_GRPC_PORT:9080}

server:
  port: ${PORT:8084}
  servlet:
    context-path: ${CONTEXT_PATH:/api/v1}

security:
  host:
    origin-allows: ${ORIGIN_ALLOWS:}
    base-host: ${BASE_HOST:}
    front-end: ${FRONTEND_URL}
    swagger-context-path: ${SWAGGER_CONTEXT_PATH:/api/v1}
    swagger-host: ${SWAGGER_HOST:}

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    org.springframework.boot.autoconfigure: OFF

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    try-it-out-enabled: true
    operations-sorter: method
    tags-sorter: alpha
    filter: true
    path: /swagger-ui