name: build-image.yaml
on:
  workflow_call:
    inputs:
      actor:
        required: true
        type: string
      repository:
        required: true
        type: string

jobs:
  build-service-image:
    name: Build API Images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ main, feedback-notification, voucher, storage, prover ]
    env:
      REGISTRY: ghcr.io/${{ inputs.repository }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ inputs.actor}}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set outputs
        id: sha-vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Build and push image
        run: |
          SERVICE=${{ matrix.service }}
          IMAGE=$REGISTRY/$SERVICE
          SHA=${{ steps.sha-vars.outputs.sha_short }}
          docker compose -f .docker/compose.build.yaml --profile ${{matrix.service}} build --parallel
          docker compose -f .docker/compose.build.yaml --profile ${{matrix.service}} push
          docker tag $IMAGE:$SHA
          docker push $IMAGE:$SHA

  build-docs-image:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io/${{ inputs.repository }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ inputs.actor}}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push image
        run: |
          docker compose -f .docker/compose.build.yaml --profile docs build --parallel
          docker compose -f .docker/compose.build.yaml --profile docs push
    
