name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Test Build (JDK 24)
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [ main, feedback-notification, voucher, storage, prover, migration ]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup JDK 24
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 24

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
          key: maven-${{ runner.os }}-jdk24-${{ matrix.service }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-jdk24-${{ matrix.service }}-
            maven-${{ runner.os }}-jdk24-
            maven-

      - name: Build only (skip tests)
        run: mvn clean install -pl :${{ matrix.service }} -am -DskipTests -B

  test:
    name: Unit Tests (JDK 24)
    runs-on: ubuntu-latest

    needs: build

    strategy:
      matrix:
        service: [ main, feedback-notification, voucher, storage, prover, migration ]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup JDK 24
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 24

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
          key: maven-${{ runner.os }}-jdk24-${{ matrix.service }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-jdk24-${{ matrix.service }}-
            maven-${{ runner.os }}-jdk24-
            maven-

      - name: Run unit tests only
        run: mvn test -pl :${{ matrix.service }} -am -B