name: Deploy / Prod
on:
  workflow_call:
    inputs:
      actor:
        required: true
        type: string
      repository:
        required: true
        type: string
jobs:
  deploy-prod:
    name: Deploy / Prod
    runs-on: retrade-prod
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY: ghcr.io/${{ inputs.repository }}
      PROTOCOL: websecure
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor}}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull Image
        run: docker compose -f .docker/compose.yaml --profile prod pull
      - name: Infisical Login
        run: |
          echo "INFISICAL_TOKEN=$(infisical login --domain=${{secrets.INFISICAL_URL}} --method=universal-auth --client-id=${{secrets.INFISICAL_CLIENT_ID}} --client-secret=${{secrets.INFISICAL_CLIENT_SECRET}} --silent --plain)" >> $GITHUB_ENV
      - name: Clean Container, Image And Prepare For Deploy
        run: infisical run --env=stag --token=${{env.INFISICAL_TOKEN}} --domain=${{secrets.INFISICAL_URL}} --projectId=${{secrets.INFISICAL_PROJECT_ID}} --path=/ --watch -- docker compose -f .docker/compose.yaml -p retrade-service --profile prod up -d
      - name: Clean Old Image
        run: docker image prune -a -f
        continue-on-error: true