on:
  push:
    branches:
      - main
      - deploy/add_migration_service
jobs:
  build-coffee-image:
    uses: ./.github/workflows/build-image.yaml
    permissions:
      contents: read
      packages: write
    with:
      actor: ${{ github.actor }}
      repository: ${{ github.repository }}
    secrets: inherit

#  deploy-dev:
#    needs: build-coffee-image
#    uses: ./.github/workflows/deploy-dev.yaml
#    permissions:
#      contents: read
#      packages: write
#    with:
#      actor: ${{ github.actor }}
#      repository: ${{ github.repository }}
#    secrets: inherit

  update-metadata:
    needs: build-coffee-image
    permissions:
      contents: write
      packages: write
    uses: ./.github/workflows/update-metadata.yaml
    with:
      services: main,feedback-notification,voucher,storage,prover
    secrets: inherit
