on:
  push:
    branches:
      - main
      - deploy/add_migration_service
jobs:
  build-coffee-image:
    uses: ./.github/workflows/build-image.yaml
    permissions:
      contents: read
      packages: write
    with:
      actor: ${{ github.actor }}
      repository: ${{ github.repository }}
    secrets: inherit

  deploy-dev:
    uses: ./.github/workflows/deploy-dev.yaml
    permissions:
      contents: read
      packages: write
    with:
      actor: ${{ github.actor }}
      repository: ${{ github.repository }}
    secrets: inherit
