on:
  push:
    branches:
      - main
      - deploy/add_migration_service
jobs:
  build-coffee-image:
    uses: ./.github/workflows/build-image.yaml
    with:
      actor: ${{ github.actor }}
      repository: ${{ github.repository }}
      token: ${{ github.token }}

  deploy-dev:
    uses: ./.github/workflows/deploy-dev.yaml
    with:
      actor: ${{ github.actor }}
      repository: ${{ github.repository }}
      token: ${{ github.token }}
    secrets:
      INFISICAL_URL: ${{secrets.INFISICAL_URL}}
      INFISICAL_CLIENT_ID: ${{secrets.INFISICAL_CLIENT_ID}}
      INFISICAL_CLIENT_SECRET: ${{secrets.INFISICAL_CLIENT_SECRET}}
      INFISICAL_PROJECT_ID: ${{secrets.INFISICAL_PROJECT_ID}}
