on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:

  test:
    name: Test / Unit
    uses: ./.github/workflows/ci-test.yaml

  build-coffee-image:
    name: Build / API
    uses: ./.github/workflows/build-image.yaml
    permissions:
      contents: read
      packages: write
    with:
      actor: ${{ github.actor }}
      repository: ${{ github.repository }}
    secrets: inherit
    if: github.event_name == 'push'

  deploy-dev:
    name: Deploy / DEV
    needs: build-coffee-image
    uses: ./.github/workflows/deploy-dev.yaml
    permissions:
      contents: read
      packages: write
    with:
      actor: ${{ github.actor }}
      repository: ${{ github.repository }}
    secrets: inherit
    if: github.event_name == 'push'

  update-metadata:
    name: Deploy / Update Metadata
    needs: [build-coffee-image, deploy-dev]
    permissions:
      contents: write
      packages: write
    uses: ./.github/workflows/update-metadata.yaml
    with:
      services: main,feedback-notification,voucher,storage,prover,migration
    secrets: inherit
    if: github.event_name == 'push'